[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Research"
  pageRef = "research"
  weight = 20

[[menus.main]]
  name = "LaTeX Notes"
  pageRef = "latex"
  weight = 25

[[menus.main]]
  name = "GitHub"
  url = "https://github.com/songyu0903"
  weight = 30
