# -- Blowfish 主题参数 --
colorScheme = "azureblue" # 自定义浅蓝配色（assets/css/schemes/azureblue.css）
defaultAppearance = "light" # light or dark

enableCodeCopy = true

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, landing
  showRecent = false
  showRecentItems = 5
  showMoreLink = false

[article]
  showDate = true
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = []

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  showSummary = true
  showDate = true

[taxonomy]
  showTermCount = true
